-- Seeds for Plants Table --

INSERT INTO plants (generic_name, specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Cucumber', 'Long English Cucumber', 'An easy-care vegetable that loves sun and water, cucumbers grow quickly as long as they receive consistent watering and warmth. Don’t let cucumbers get too large before you pick or they will taste bitter!', 'https://images.pexels.com/photos/128420/pexels-photo-128420.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'April to June', 3, 'Indirect Sun', 1, 40, '6 inches apart', 'One inch deep', '50 to 70 days');

INSERT INTO plants (generic_name, specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Tomato', 'Cherry Tomato', 'These succulent, bite-sized jewels concentrate all the flavor of a full sized tomato into a package that is less than 2" in diameter. They are sweeter, perfectly shaped, and have thinner skin than regular tomatoes.', 'https://images.pexels.com/photos/8857067/pexels-photo-8857067.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'May to August', 3, 'Direct Sun', 0, 35, '24 inches apart', 'At least 1/2 inch deep', '55 to 65 days');

INSERT INTO plants (generic_name, specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Kale', 'Common Curly Kale', 'Ever been told to “eat your greens?” Kale is one of the most nutritious vegetables you can grow. It’s crammed with vitamins and powerful antioxidants, and it tastes de-licious.', 'https://images.pexels.com/photos/134877/pexels-photo-134877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'May to early July', 1, 'Shade', 10, 25, '1 to 2 feet apart', 'At least 1/2 inch deep', '90 days');

INSERT INTO plants (generic_name, specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Potato', 'Sweet Potato', 'Sweet potatoes are a staple food in many parts of the world. They are a good source of fiber, potassium, vitamins, and other essential nutrients.', 'https://images.pexels.com/photos/89247/pexels-photo-89247.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'April to August', 3, 'Direct Sun', 0, 45, '12 inches apart', '6 inches deep', '90 to 170 days');

INSERT INTO plants (generic_name, specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Squash', 'Butternut Squash', 'With its ability to taste sweet or savory, butternut squash is a versatile staple in autumn and winter cooking.', 'https://images.pexels.com/photos/6316531/pexels-photo-6316531.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'May to early July', 1, 'Direct Sun', 10, 38, '4 inches apart', '1 to 1/2 inches deep', '50 to 55 days');

INSERT INTO plants (generic_name, specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Cabbage', 'Red Cabbage', 'Red cabbage is a nutrient-rich, cruciferous, or Brassica vegetable.', 'https://images.pexels.com/photos/8859770/pexels-photo-8859770.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'March to June', 1, 'Direct Sun', 0, 25, '12-14 inches apart', '4 inches deep', '60 days');