INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Pansy', 'The Garden Pansy is a type of large-flowered hybrid plant that come in a variety of lively colour combinations. A hardy plant, they love sun and well-draining soils.', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/pansyPicture.jpeg?raw=true', 'April to June', 3, 'Direct Sun', 1, 35, '5 inches apart', 'One inch deep', '60 to 80 days');

INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Clematis', 'Clematis are woody, climbing vines with both deciduous and evergreen species. They grow best in cool, moist soil, and are popular in West Coast gardens', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/clematisPicture.jpeg?raw=true', 'March to April', 5, 'Direct Sun', 5, 40, '1 inch apart', '1/2 inch deep', '30 to 60 days');

INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Hybrid Tea Rose', 'Hybrid teas are one of the most popular garden shrubs in the world with both indoor and outdoor appeal. They are grown in a large variety of colours.', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/rosePicture.jpeg?raw=true', 'April to May', 7, 'Indirect Sun', 8, 37, '3 inches apart', '1/4 inch deep', '70 to 80 days');

INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Dahlia', 'Dahlias are bushy, tuberous, herbaceous perennial plants, and are the national flower of Mexico. Dahlia tubers can be removed from the ground and stored during the winter, making them a versatile plant.', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/dahliaPicture.jpeg?raw=true', 'April to June', 3, 'Direct Sun', 8, 37, '10 inches apart', '6 inches deep', '65 to 75 days');

INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Daffodil', 'Daffodils, also called narcissuses or jonquils, are a blub planted to bring colour to a garden in early Spring. ', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/daffodilPicture.jpeg?raw=true', 'September to October', 6, 'Direct Sun', 0, 40, '4 inches apart', '7 inches deep', '80 to 100 days');

INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Common Poppy', 'Poppies are herbaceous plants, often grown for their colourful flowers that come in varied hues of red, blue and orange. The image of a poppy has had various meanings over the centuries, popularly as a symbol for opium and for Remembrance Day.', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/poppyPicture.jpeg?raw=true', 'March to April', 4, 'Direct Sun', 10, 40, '1/4 inch apart', '1/2 inch deep', '60 to 70 days');

INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Hydrangea', 'Hydrangea or hortensia is a genus of over 75 species of flowering plants native to Asia and the Americas, most commonly found in China, Korea and Japan. Most are shrubs, but some are small trees or vines.', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/hydrangeaPicture.jpeg?raw=true', 'April to June', 7, 'Shade', 10, 40, '1 inch apart', '1/4 inch deep', '70 to 80 days');

INSERT INTO plants (specific_name, description, large_plant_card_photo_url, when_to_plant, water_needs, sunlight_needs, lowest_temp_tolerance, highest_temp_tolerance, how_far_apart_to_plant, how_deep_to_plant, how_long_until_mature) VALUES ('Sunflower', 'The common sunflower is a large, annual herbaceous plant grown as a crop for its edible oil and seeds. The beautiful, bright flowers are harvested in later Summer and early Fall.', 'https://github.com/MatiasWengiel/HomeGardnr--Caitlin-Croteau-Raiza-DeGuzman-Matias-Wengiel/blob/main/project-organization/plant-pics/sunflowerPicture.jpeg?raw=true', 'April to May', 7, 'Direct Sun', 5, 35, '12 inches apart', '1 inch deep', '80 to 100 days');